description: Mostly Basic Python Problems (MBPP)
eval_mode: opencompass
name: smith-mbpp
opencompass_dataset: opencompass.configs.datasets.mbpp.mbpp_gen_830460
source:
  hf_dataset: google-research-datasets/mbpp
  hf_split: test
  hf_subset: full
  max_samples: 50
task_type: code
